# Generated by Django 3.1.4 on 2020-12-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date create')),
                ('avatar', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
