# Generated by Django 3.1.4 on 2020-12-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_auto_20201205_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
