# Generated by Django 3.1.4 on 2020-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_auto_20201205_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(verbose_name='date start'),
        ),
    ]
