# Generated by Django 3.1.4 on 2020-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_auto_20201205_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(verbose_name='date create'),
        ),
    ]
