# Generated by Django 3.1.4 on 2020-12-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_task_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
    ]
